steps:
  - name: 'gcr.io/cloud-builders/go'
    args: ["run", "main.go"]
    env: ['GOPATH=$HOME/src/golang-ci/']

  - name: 'gcr.io/cloud-builders/go'
    args: ["test", "-vet=off"]
    env: ['GOPATH=$HOME/src/golang-ci/']



